spring:
  application:
    name: dreams-logistics-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    gateway:
      routes:
        - id: dreams-logistics-auth-service
          uri: lb://dreams-logistics-auth-service
          predicates:
            - Path=/api/auth/**
        - id: dreams-logistics-user-service
          uri: lb://dreams-logistics-user-service
          predicates:
            - Path=/api/user/**
        - id: dreams-logistics-article-service
          uri: lb://dreams-logistics-article-service
          predicates:
            - Path=/api/article/**
        - id: dreams-logistics-resource-service
          uri: lb://dreams-logistics-resource-service
          predicates:
            - Path=/api/resource/**
        - id: dreams-logistics-transport-service
          uri: lb://dreams-logistics-transport-service
          predicates:
            - Path=/api/transport/**
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000
    password: 123456

  # 解决 Description:Spring MVC found on classpath, which is incompatible with Spring Cloud Gateway.
  #Action:Please set spring.main.web-application-type=reactive or remove spring-boot-starter-web dependency.
  main:
    web-application-type: reactive

server:
  port: 8101


knife4j:
  gateway:
    # ① 第一个配置，开启gateway聚合组件
    enabled: true
    # ② 第二行配置，设置聚合模式采用discover服务发现的模式
    strategy: discover
    discover:
      # ③ 第三行配置，开启discover模式
      enabled: true
      # ④ 第四行配置，聚合子服务全部为Swagger2规范的文档
      version: swagger2
